spring:
  application:
    name: chart
  datasource:
      url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost/db_chart}
      username: ${JDBC_DATABASE_USERNAME:develop}
      password: ${JDBC_DATABASE_PASSWORD:123456}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: false
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


#spring.flyway.enabled=false
#spring.flyway.baseline-on-migrate=true
#spring.flyway.baseline-version=1

chart:
  server:
    host: cyrillworkchart.herokuapp.com
    port: ${process.env.PORT:1234}

  mail:
    host: smtp.yandex.ru
    username: chartchart@yandex.ru
    password: qwerasdfzxcv
    port: 465
    protocol: smtps
    debug: true

  upload:
    path: /tmp/uploads/

  recaptcha: 6Lf13roUAAAAAOhgqFhx1BASz7KlnCagl7TGdHdT

  recaptcha.url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

#windows
#    path: D:\uploads\

server:
  host: cyrillworkchart.herokuapp.com
  port: ${process.env.PORT:1234}


logging.level.com.cyrillwork.chart: DEBUG
